### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by harshit1142** [harshit1142/albums#1]

**Comment by idk-mr4tyunjay** [comment]
Can you assign this issue to me?

**Comment by harshit1142** [comment]
@idk-mr4tyunjay Yes, you can work on this issue. Star ⭐ the project and follow me to start.

**Comment by idk-mr4tyunjay** [comment]
Hi @harshit1142,
I have starred the project and dropped a follow. 
Could you please provide some more details about the purpose and goals of the website? Understanding what it should be about will help me work on it more effectively.

**Comment by harshit1142** [comment]
@idk-mr4tyunjay 
It is a simple website for searching for an album in the database. We implemented some functionality for searching efficiently.
